# Generated by Django 3.0.4 on 2020-06-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.TextField(default='poker_room'),
            preserve_default=False,
        ),
    ]
