# Generated by Django 3.0.4 on 2020-09-11 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0005_auto_20200822_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='test',
        ),
    ]
