version: '3.7'

services:
  redis:
    image: redis
    command: redis-server
    ports:
      - '6379:6379'
  
  src:
    build:
      context: .
    ports:
    - '8000:8000'
    volumes:
      - static_data:/vol/web/static
      - media_data:/vol/web/media
    command: uwsgi --socket :8000 --master --enable-threads --module poker_base.wsgi
    environment:
      - DEBUG=1
    depends_on:
      - db

  channels:
    build:
      context: .
    command: daphne -b 0.0.0.0 -p 8001 poker_base.asgi:application
    volumes:
      - ./src:/src
    ports:
      - '8001:8001'
    links:
      - redis
  
  worker:
    build:
      context: .
    command: python manage.py runworker poker_game
    links:
    - redis
    depends_on:
     - src
  
  proxy:
    build:
      context: ./proxy
    volumes:
     - static_data:/vol/static
     - media_data:/vol/media
    ports:
     - '80:80'
    depends_on:
      - src
  
  db:
    image: postgres
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  static_data:
  postgres_data:
  media_data:
